- name: Build and compress executable with auto-missing dependency install
  run: |
    MAX_ATTEMPTS=5
    ATTEMPT=1
    while [ $ATTEMPT -le $MAX_ATTEMPTS ]; do
      echo "Build attempt $ATTEMPT"
      set +e
      pyinstaller --onefile --noconfirm --strip --exclude-module onnxscript --exclude-module pyodide textStudy/main.py 2> build.log
      EXIT_CODE=$?
      set -e
      if [ $EXIT_CODE -eq 0 ]; then
        echo "PyInstaller build succeeded!"
        break
      fi
      # Detect missing module from the log
      MISSING=$(grep -oP "No module named '\K[^']+" build.log | head -1)
      if [ ! -z "$MISSING" ]; then
        echo "Auto-installing missing module: $MISSING"
        pip install "$MISSING"
      else
        echo "Build failed, but no missing module detected."
        cat build.log
        exit 1
      fi
      ATTEMPT=$((ATTEMPT+1))
    done
    if [ $EXIT_CODE -ne 0 ]; then
      echo "PyInstaller build failed after $MAX_ATTEMPTS attempts."
      exit 1
    fi
    mv dist/main dist/textStudy-linux
    upx --best --lzma dist/textStudy-linux
    tar -czf textStudy-linux.tar.gz -C dist textStudy-linux
