name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Download FFmpeg
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            wget -O ffmpeg.tar.xz https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
            tar -xf ffmpeg.tar.xz
            cp ffmpeg-*-amd64-static/ffmpeg .
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            curl -L -o ffmpeg.zip https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip
            unzip ffmpeg.zip
            cp ffmpeg-*-essentials_build/bin/ffmpeg.exe .
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            brew install ffmpeg
            which ffmpeg
            cp $(which ffmpeg) .
          fi

      - name: Build executable
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            pyinstaller --onefile textStudy/main.py --name textstudy --add-binary "ffmpeg.exe;."
          else
            pyinstaller --onefile textStudy/main.py --name textstudy --add-binary "ffmpeg:."
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: textstudy-${{ runner.os }}
          path: dist/textstudy*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: dist

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**/textstudy*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 